### ISSUE TITLE
Please provide example datapack

### ISSUE THREAD

**Issue by Silenc42** [Crystal-Nest/server-sided-portals#1]
### I have confirmed no other issue asks for this

- [X] I have searched for existing issues

### What needs an update

datapack usage documentation

### Current documentation content

Currently there is a 5-step outline for creating a datapack with links to the official wiki.
An example is provided for a mod, but not for datapack usage.

### Change reason

The current how-to is very high level and requires research if one is not familiar with the details of datapacks.
It would be much easier, if there was a simple datapack I could copy and adjust.

After hours, I managed to create a dimension and the block tag as described; I can teleport to the dimension via commands and I can verify the tag in the F3 debug view. Still no portal connection is established. I can only assume that there's an error somewhere in my datapack's structure.

### Desired changes

Please provide a simple, but working datapack, e.g. for generating a second overworld dimension and using netherrack as a portal block.

**Comment by Crystal-Spider** [comment]
Sure thing!

**Comment by Crystal-Spider** [comment]
You can find a specific section of the Wiki about working examples [here](https://github.com/Crystal-Nest/server-sided-portals/wiki/Working-examples).  
In particular, you can find the up-to-date working datapack example [here](https://github.com/Crystal-Nest/ssp-datapack-example), available for all supported Minecraft versions.

**Comment by Crystal-Spider** [comment]
If you need any further assistance, you can hop on our Discord for an easy chat!

**Comment by Silenc42** [comment]
Thank you very much! Awesome response time ;)
